In [152]:
import pandas as pd
import numpy as np

In [153]:
# data extracted from https://toronto.weatherstats.ca/download.html
df = pd.read_csv('weatherstats_toronto_normal_daily.csv')
df.head()

,date,max_dew_point_v,max_dew_point_s,max_dew_point_c,max_dew_point_d,max_relative_humidity_v,max_relative_humidity_s,max_relative_humidity_c,max_relative_humidity_d,max_temperature_v,...,snow_c,snow_d,snow_on_ground_v,snow_on_ground_s,snow_on_ground_c,snow_on_ground_d,solar_radiation_v,solar_radiation_s,solar_radiation_c,solar_radiation_d
0,2021-02-28,-3.79,6.19,450,1991-02-21 2020-03-06,84.47,9.73,450,1991-02-21 2020-03-06,1.29,...,448,1991-02-21 2020-03-06,5.3,6.75,419,1991-02-21 2020-03-06,NaN,NaN,NaN,NaN
1,2021-02-27,-3.83,6.23,450,1991-02-20 2020-03-05,84.49,9.78,450,1991-02-20 2020-03-05,1.21,...,449,1991-02-20 2020-03-05,5.1,6.61,419,1991-02-20 2020-03-05,NaN,NaN,NaN,NaN
2,2021-02-26,-3.80,6.19,450,1991-02-19 2020-03-04,84.34,9.78,450,1991-02-19 2020-03-04,1.22,...,449,1991-02-19 2020-03-04,5.1,6.53,420,1991-02-19 2020-03-04,NaN,NaN,NaN,NaN
3,2021-02-25,-3.77,6.26,450,1991-02-18 2020-03-03,84.52,9.75,450,1991-02-18 2020-03-03,1.16,...,449,1991-02-18 2020-03-03,5.1,6.47,422,1991-02-18 2020-03-03,NaN,NaN,NaN,NaN
4,2021-02-24,-3.77,6.26,450,1991-02-17 2020-03-02,84.68,9.62,450,1991-02-17 2020-03-02,1.08,...,449,1991-02-17 2020-03-02,5.3,6.71,423,1991-02-17 2020-03-02,NaN,NaN,NaN,NaN

In [154]:
# data cleaning and prep
# get rid of unnecessary columns for data prediction 
# partition date and filter for 2020 data
# get day of the week fields for each entry
# one-hot encoding data (categorical data)

In [155]:
df.columns

Index(['date', 'max_dew_point_v', 'max_dew_point_s', 'max_dew_point_c',
       'max_dew_point_d', 'max_relative_humidity_v', 'max_relative_humidity_s',
       'max_relative_humidity_c', 'max_relative_humidity_d',
       'max_temperature_v', 'max_temperature_s', 'max_temperature_c',
       'max_temperature_d', 'max_wind_speed_v', 'max_wind_speed_s',
       'max_wind_speed_c', 'max_wind_speed_d', 'min_dew_point_v',
       'min_dew_point_s', 'min_dew_point_c', 'min_dew_point_d',
       'min_relative_humidity_v', 'min_relative_humidity_s',
       'min_relative_humidity_c', 'min_relative_humidity_d',
       'min_temperature_v', 'min_temperature_s', 'min_temperature_c',
       'min_temperature_d', 'min_wind_speed_v', 'min_wind_speed_s',
       'min_wind_speed_c', 'min_wind_speed_d', 'precipitation_v',
       'precipitation_s', 'precipitation_c', 'precipitation_d', 'rain_v',
       'rain_s', 'rain_c', 'rain_d', 'snow_v', 'snow_s', 'snow_c', 'snow_d',
       'snow_on_ground_v', 'snow_on_ground_s', 'snow_on_ground_c',
       'snow_on_ground_d', 'solar_radiation_v', 'solar_radiation_s',
       'solar_radiation_c', 'solar_radiation_d'],
      dtype='object')

In [156]:
df.drop(df.columns[[2, 3, 4, 6, 7, 8, 10, 11, 12, 14, 15, 16, 18, 19, 20, 22, 23, 24, 26, 27, 28, 30, 31, 32, 34, 35, 36, 38, 39, 40, 42, 43, 44, 46, 47, 48, 50, 51, 52]], axis = 1, inplace = True)

In [157]:
df.head(10)

,date,max_dew_point_v,max_relative_humidity_v,max_temperature_v,max_wind_speed_v,min_dew_point_v,min_relative_humidity_v,min_temperature_v,min_wind_speed_v,precipitation_v,rain_v,snow_v,snow_on_ground_v,solar_radiation_v
0,2021-02-28,-3.79,84.47,1.29,30.86,-11.07,56.77,-7.04,5.82,1.92,1.03,0.94,5.3,NaN
1,2021-02-27,-3.83,84.49,1.21,30.90,-11.00,57.04,-7.00,5.89,1.93,1.01,0.97,5.1,NaN
2,2021-02-26,-3.80,84.34,1.22,31.03,-11.04,57.33,-7.05,5.96,1.84,1.01,0.85,5.1,NaN
3,2021-02-25,-3.77,84.52,1.16,31.34,-11.05,57.64,-7.07,5.86,1.79,0.99,0.82,5.1,NaN
4,2021-02-24,-3.77,84.68,1.08,31.18,-11.17,58.00,-7.25,5.61,1.83,1.05,0.80,5.3,NaN
5,2021-02-23,-3.80,84.88,0.99,30.93,-11.23,58.10,-7.35,5.41,1.89,1.04,0.88,5.4,NaN
6,2021-02-22,-3.92,84.84,0.83,30.82,-11.39,58.32,-7.51,5.46,1.86,1.06,0.84,5.5,NaN
7,2021-02-21,-4.12,84.67,0.62,30.67,-11.56,58.34,-7.65,5.60,1.85,1.03,0.85,5.6,NaN
8,2021-02-20,-4.29,84.67,0.35,30.92,-11.81,58.41,-7.85,5.77,1.81,0.96,0.89,5.7,NaN
9,2021-02-19,-4.38,84.72,0.17,31.11,-12.04,58.35,-8.08,5.92,1.78,0.94,0.90,5.7,NaN

In [158]:
df.loc[df['date'] == '2020-06-21']

,date,max_dew_point_v,max_relative_humidity_v,max_temperature_v,max_wind_speed_v,min_dew_point_v,min_relative_humidity_v,min_temperature_v,min_wind_speed_v,precipitation_v,rain_v,snow_v,snow_on_ground_v,solar_radiation_v
252,2020-06-21,16.02,84.66,25.58,25.8,10.14,48.49,14.94,3.38,2.57,2.57,0.0,0.0,NaN

In [159]:
# split up date into year, month, and day columns
year = df['date'].apply(lambda x: x.split('-', 1)[0])
df['year'] = year
month = df['date'].apply(lambda x: x.split('-')[1])
df['month'] = month
day = df['date'].apply(lambda x: x.split('-')[2])
df['day'] = day
df.head()

,date,max_dew_point_v,max_relative_humidity_v,max_temperature_v,max_wind_speed_v,min_dew_point_v,min_relative_humidity_v,min_temperature_v,min_wind_speed_v,precipitation_v,rain_v,snow_v,snow_on_ground_v,solar_radiation_v,year,month,day
0,2021-02-28,-3.79,84.47,1.29,30.86,-11.07,56.77,-7.04,5.82,1.92,1.03,0.94,5.3,NaN,2021,02,28
1,2021-02-27,-3.83,84.49,1.21,30.90,-11.00,57.04,-7.00,5.89,1.93,1.01,0.97,5.1,NaN,2021,02,27
2,2021-02-26,-3.80,84.34,1.22,31.03,-11.04,57.33,-7.05,5.96,1.84,1.01,0.85,5.1,NaN,2021,02,26
3,2021-02-25,-3.77,84.52,1.16,31.34,-11.05,57.64,-7.07,5.86,1.79,0.99,0.82,5.1,NaN,2021,02,25
4,2021-02-24,-3.77,84.68,1.08,31.18,-11.17,58.00,-7.25,5.61,1.83,1.05,0.80,5.3,NaN,2021,02,24

In [160]:
# filter for rows such that year = 2020 for training model
df = df.loc[df['year'] == '2020']
df.head()

,date,max_dew_point_v,max_relative_humidity_v,max_temperature_v,max_wind_speed_v,min_dew_point_v,min_relative_humidity_v,min_temperature_v,min_wind_speed_v,precipitation_v,rain_v,snow_v,snow_on_ground_v,solar_radiation_v,year,month,day
59,2020-12-31,-3.29,87.90,0.12,30.47,-10.39,64.52,-6.93,6.34,1.79,1.09,0.77,3.5,NaN,2020,12,31
60,2020-12-30,-3.02,88.11,0.36,30.40,-10.09,64.89,-6.66,6.33,1.95,1.21,0.78,3.5,NaN,2020,12,30
61,2020-12-29,-2.85,88.16,0.54,30.42,-9.82,64.95,-6.38,6.48,1.96,1.26,0.75,3.5,NaN,2020,12,29
62,2020-12-28,-2.72,88.20,0.70,30.42,-9.64,65.00,-6.23,6.39,1.99,1.32,0.72,3.5,NaN,2020,12,28
63,2020-12-27,-2.70,88.15,0.73,30.21,-9.66,64.77,-6.26,6.27,1.97,1.29,0.73,3.6,NaN,2020,12,27

In [161]:
# Check for missing data
df.shape

(366, 17)

In [162]:
# We see that since 2020 was a leap year, there should be 366 rows

In [163]:
d = datetime.datetime(2010, 10, 29).weekday()
print(d)

4

In [164]:
# convert year, month, day into numeric data
df[['year', 'month', 'day']] = df[['year', 'month', 'day']].apply(pd.to_numeric)

In [165]:
# get day of the week fields for each row
import datetime
weekday = df.apply(lambda x: datetime.datetime(x.year, x.month, x.day).weekday(), axis=1)
df['weekday'] = weekday
df.head()

,date,max_dew_point_v,max_relative_humidity_v,max_temperature_v,max_wind_speed_v,min_dew_point_v,min_relative_humidity_v,min_temperature_v,min_wind_speed_v,precipitation_v,rain_v,snow_v,snow_on_ground_v,solar_radiation_v,year,month,day,weekday
59,2020-12-31,-3.29,87.90,0.12,30.47,-10.39,64.52,-6.93,6.34,1.79,1.09,0.77,3.5,NaN,2020,12,31,3
60,2020-12-30,-3.02,88.11,0.36,30.40,-10.09,64.89,-6.66,6.33,1.95,1.21,0.78,3.5,NaN,2020,12,30,2
61,2020-12-29,-2.85,88.16,0.54,30.42,-9.82,64.95,-6.38,6.48,1.96,1.26,0.75,3.5,NaN,2020,12,29,1
62,2020-12-28,-2.72,88.20,0.70,30.42,-9.64,65.00,-6.23,6.39,1.99,1.32,0.72,3.5,NaN,2020,12,28,0
63,2020-12-27,-2.70,88.15,0.73,30.21,-9.66,64.77,-6.26,6.27,1.97,1.29,0.73,3.6,NaN,2020,12,27,6

In [166]:
# dummy variable for weekday
df = pd.get_dummies(df, columns=['weekday'])

In [167]:
df.head()

,date,max_dew_point_v,max_relative_humidity_v,max_temperature_v,max_wind_speed_v,min_dew_point_v,min_relative_humidity_v,min_temperature_v,min_wind_speed_v,precipitation_v,...,year,month,day,weekday_0,weekday_1,weekday_2,weekday_3,weekday_4,weekday_5,weekday_6
59,2020-12-31,-3.29,87.90,0.12,30.47,-10.39,64.52,-6.93,6.34,1.79,...,2020,12,31,0,0,0,1,0,0,0
60,2020-12-30,-3.02,88.11,0.36,30.40,-10.09,64.89,-6.66,6.33,1.95,...,2020,12,30,0,0,1,0,0,0,0
61,2020-12-29,-2.85,88.16,0.54,30.42,-9.82,64.95,-6.38,6.48,1.96,...,2020,12,29,0,1,0,0,0,0,0
62,2020-12-28,-2.72,88.20,0.70,30.42,-9.64,65.00,-6.23,6.39,1.99,...,2020,12,28,1,0,0,0,0,0,0
63,2020-12-27,-2.70,88.15,0.73,30.21,-9.66,64.77,-6.26,6.27,1.97,...,2020,12,27,0,0,0,0,0,0,1

In [169]:
# export csv
df.to_csv('clean_weather_data.csv')